# netlify.toml
[build]
  command   = "npm install"
  functions = "functions"
  publish   = "."        # we’re only serving functions, no "public" folder

[dev]
  functions = "functions"

# 1) Redirect root → /bot
[[redirects]]
  from    = "/"
  to      = "/.netlify/functions/bot"
  status  = 200
  force   = true
  methods = ["GET","POST"]

# 2) Then /bot → your Netlify Function
[[redirects]]
  from    = "/bot"
  to      = "/.netlify/functions/bot"
  status  = 200
  force   = true
  methods = ["GET","POST"]
