# netlify.toml
[build]
  command   = "npm install"
  functions = "functions"
  publish   = "."

[dev]
  functions = "functions"

# ------------------------------------------------
# CATCH-ALL → send EVERYTHING to your bot function
[[redirects]]
  from     = "/*"
  to       = "/.netlify/functions/bot"
  status   = 200
  force    = true
  methods  = ["GET","POST"]
