# netlify.toml
[build]
  command   = "npm install"
  functions = "functions"
  publish   = "."           # we’re only serving functions, no "public" folder

[dev]
  functions = "functions"

# route /bot → our serverless function named "bot"
[[redirects]]
  from    = "/bot"
  to      = "/.netlify/functions/bot"
  status  = 200
  force   = true
  methods = ["GET","POST"]
